### ISSUE TITLE
Compile error with GHC 7.4.2

### ISSUE THREAD

**Issue by hvr** [emilaxelsson/operational-alacarte#1]
`build-depends` states that this package is compatible with base-4.5/GHC-7.4.2, however GHC disagrees:

```
Configuring component lib from operational-alacarte-0.3
Warning: 'hs-source-dirs: examples' directory does not exist.
Preprocessing library operational-alacarte-0.3...
[1 of 2] Compiling Data.ALaCarte    ( src/Data/ALaCarte.hs, /tmp/matrix-worker/1480524560/dist-newstyle/build/x86_64-linux/ghc-7.4.2/operational-alacarte-0.3/build/Data/ALaCarte.o )

src/Data/ALaCarte.hs:166:23:
    Couldn't match kind `BOX' against `*'
    Kind incompatibility when matching types:
      k0 :: BOX
      (k -> *, k2) :: *
    In the return type of a call of `Inl'
    In the expression: Inl (hfmap f i)

src/Data/ALaCarte.hs:181:26:
    Couldn't match kind `BOX' against `*'
    Kind incompatibility when matching types:
      k0 :: BOX
      (* -> *, (k1 -> *, k2)) :: *
    In the return type of a call of `Inl'
    In the expression: Inl (hbimap f g i)
```

**Comment by emilaxelsson** [comment]
Sorry, I've been snowed under for a while.
Thanks for the report! I've fixed it now.

Out of curiosity, does this cause a problem somewhere in the ecosystem? (I'm assuming you didn't discover it as a user of the package, or did you?)

**Comment by hvr** [comment]
@emilaxelsson this was detected by the Hackage matrix builder, I don't think it was actually causing problems, but the more popular your package becomes, the more likely it becomes

Fwiw, that package has already 5 revdeps on Hackage:

http://packdeps.haskellers.com/reverse/operational-alacarte
